// app/layout.tsx
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/providers/modal-provide';
import prismaClient from '@/lib/prismaClient';
import Providers from '@/providers/providers';
import './globals.css'
import { Header } from '@/components/header';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Header />
            <div
              className={cn(
                "h-screen overflow-auto border-t bg-background pb-8",
                // "scrollbar-none"
                "scrollbar scrollbar-track-transparent scrollbar-thumb-accent scrollbar-thumb-rounded-md"
              )}>
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </ClerkProvider>

  )
}
